/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package testDrive1.app

import testDrive1.utilities.StringUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    println(StringUtils.join(tokens))
}
