/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package testDrive1.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      Prism!"
    }
}
